apiVersion: v1
kind: Pod
metadata:
  annotations:
    wavy.squat.ai/enable: "true"
  labels:
    app.kubernetes.io/name: insomnia
  name: insomnia
spec:
  containers:
  - image: kasmweb/insomnia:1.13.1
    name: insomnia
    command:
    - /usr/bin/insomnia
    args:
    - --no-sandbox
